$(document).ready(function(){
	$(".pilih-jadwal-group6").click(function(){
		//$(".header-block-item-layanan").hide();
		$(this).toggleClass('pilih-jadwal-group6-clicked');
 });
	$(".pilih-jadwal-txt21.layout").click(function(){
		//$(".header-block-item-layanan").hide();
		window.location.href="PilihPembayaran.html";
});
});