$(document).ready(function(){
	$(".register-block4.layout").click(function(){
		//$(".header-block-item-layanan").hide();
		window.location.href="Register.html";
 });
	$(".register-block20.layout").click(function(){
		//$(".header-block-item-layanan").hide();
		window.location.href="index.html";
 });
});